[advisories]
ignore = [
    # Non-utf8 String can be created with `TimeBuf::as_str`
    "RUSTSEC-2025-0140",
    # proc-macro-error2 is unmaintained (via defmt)
    "RUSTSEC-2026-0173",
]

[output]
quiet = false
deny = ["warnings"]
