[advisories]
ignore = [
    # proc-macro-error2 is unmaintained (via defmt)
    "RUSTSEC-2026-0173",
]

show = ["unmaintained", "unsound"]
fatal = ["critical"]

[output]
quiet = false
deny = ["warnings"]
