[package]
name         = "cargo-audit"
description  = "Audit Cargo.lock for crates with security vulnerabilities"
version      = "0.21.2"
authors      = ["Tony Arcieri <bascule@gmail.com>"]
license      = "Apache-2.0 OR MIT"
homepage     = "https://rustsec.org"
repository   = "https://github.com/rustsec/rustsec"
readme       = "README.md"
categories   = ["development-tools::cargo-plugins"]
keywords     = ["cargo-subcommand", "security", "audit", "vulnerability"]
edition      = "2021"
rust-version = "1.85"
exclude      = ["tests/"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
abscissa_core = { workspace = true }
cargo-lock = { workspace = true }
clap = { workspace = true }
home = { workspace = true }
rustsec = { workspace = true, features = ["dependency-tree"] }
serde = { workspace = true, features = ["serde_derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
display-error-chain = { workspace = true }

[dev-dependencies]
abscissa_core = { workspace = true, features = ["testing"] }
once_cell = { workspace = true }
tempfile = { workspace = true }
toml = { workspace = true }

[features]
default = ["binary-scanning"]
fix = []
binary-scanning = ["rustsec/binary-scanning"]
