name: platforms-update

permissions: {}

on:
  schedule:
    - cron: "27 3 * * 5"
  workflow_dispatch:

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Regenerate platform files
        run: |
          cd platforms
          ./regenerate-platforms-crate.sh
          git diff --exit-code
